### ISSUE TITLE
Review instruction text in circuit breaker guide.

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguide-circuit-breaker#157]
Review the text in the circuit breaker guide to update directional statements such as 

"..in the following browser"

to something more appropriate for the new multi-pane design.  Remember that the text has to make sense in both single and multi-column views.   

For example, "..in the following browser" could change to "...in the browser for this section"?

Also, we had to get rid of 'Save' in the playground editors since we have a common editor for the step and the playground now.   So, change all references to 'Save' to now be 'Run'.

**Comment by amyreit** [comment]
Changed all the references to the "following browser" to just "browser" because with the snap scrolling saying "in this section" seemed unnecessary. You can only see one browser.  

Also, didn't need to change any of the Save's to Run because of the discussion we had with the team.  I added "in the editor" in a couple of places just to make it more complete - not really required and can be removed if they add too many extra words.
