### ISSUE TITLE
"Half-open" introduced but not explained until late

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/iguide-circuit-breaker#46]
In the "Configure a delay" section, the concept of "half-open" is introduced, and it says, "...the circuit changes to the half-open state and checks if the main service is healthy ".  It's not clear what that really means and the interactive section on that same page does not clarify it.  I'm left wondering, how does it do the check, and what are the consequences of healthy vs unhealthy?  The description makes it sound like a pro-active check, rather than just a check on the next request.  When I do the interactive part, the timer runs down and then says the circuit is half-open, but all I can do is "reset", so it doesn't help me understand what's happened.  I found the next page clarified everything, so this could be fixed by a) rewording the section that implies a pro-active check and b), forward reference the next section to say more details on half-open will follow.

**Comment by kevinwlau** [comment]
@gcharters A general description of the half-open state is introduced in the Background Concepts in the first page. The description in the "Configuring the success threshold" goes a little more into detail.

Would it suffice to remove "and checks if the main service is healthy" to not make it sound proactive?

**Comment by gcharters** [comment]
Hi @steven1046 , sorry, I didn't see @kevinwlau 's question until now. Were any changes made as a result of this?

**Comment by steven1046** [comment]
Hi @gcharters, we changed "By default, the circuit remains open for 5000 ms. During this period, all requests to the main service are blocked and fail immediately. At the end of this period, the circuit changes to the half-open state and checks if the main service is healthy. This time period can be configured with the delay parameter." to "By default, the circuit remains open for 5000 ms. You can configure the number of milliseconds with the delay parameter. During the period that the circuit remains open, all requests to the main service are blocked and fail immediately. At the end of this period, the circuit changes to the half-open state. This half-open state is a temporary state where further requests to the main microservice are allowed through and checked for success or failure." so it will explain the half-open state briefly before it talks about it a lot more in the next section. Also we got rid of the confusing stanza about checking if the microservice is healthy since the delay section doesn't really go into detail about that.

**Comment by gcharters** [comment]
@steven1046 - awesome.  thanks! :)
