### ISSUE TITLE
Add reference to server.xml step to both "add annotation" steps

### ISSUE THREAD

**Issue by dlp01** [OpenLiberty/iguide-circuit-breaker#53]
We got feedback from a user of the Circuit Breaker guide that, after following the steps in the guide and the annotations didn't work.  Obviously, he didn't follow ALL the steps, but we don't require folks to do so.  Once he updated his server.xml, he was off to the races.

Given that feedback, we need to make it more clear that the server.xml change is required to make any of the annotations work.  So, for both sections: 

- Adding the @CircuitBreaker annotation
- Adding the @Fallback annotation

we need to add a single line or part of a line to say "After having modified server.xml to include the fault tolerance feature, " ... and make that clickable so that the user can go to the step that illustrates that.

**Comment by dmorgant** [comment]
In order to emphasize that the suggested annotations will only work in your code if the MicroProfile fault taolerance feature is enabled in your server.xml, we will make the following changes:

We have an 'Enabling MicroProfile Fault Tolerance' step in our guide where we discuss how to add the feature in your server.xml.

Following that step we have an 'Adding the @CircuitBreaker annotation' step.  I would like to change the opening sentence from 
	Let's add a default CircuitBreaker policy to the Check Balance microservice. 
to 
	After modifying your server.xml to _include the fault tolerance feature_, add a default CircuitBreaker policy to the Check Balance microservice. 


And similarly, in the 'Adding the @Fallback annotation' step, we want to change the opening sentence from 
	We use the @Fallback annotation to identify a method that runs when the Check Balance microservice fails.
to 
	After modifying your server.xml to _include the fault tolerance feature_, use the @Fallback annotation to identify a method that runs when the Check Balance microservice fails.  


In both sentences, the '_include the fault tolerance feature_' part will be a link that when selected will go to the the 'Enabling MicroProfile Fault Tolerance' step that describes how to add the feature in your server.xml.

Trying to contact Karen Deen for ID approval on the new sentences.

**Comment by chirp1** [comment]
Since the mpFaultTolerance-1.0 feature is required, how about if on the "Enabling MicroProfile fault tolerance" page we change "This feature provides an environment to support resilient microservices..." to "This feature is required and provides an environment to support resilient microservices..."?

Change "After modifying your server.xml to include the fault tolerance feature, add a default CircuitBreaker policy to the Check Balance microservice." to "After you modify your `server.xml` file to include the fault tolerance feature, add a default CircuitBreaker policy to the Check Balance microservice."

On that same page we have "Add the @CircuitBreaker annotation on line 6, above the checkBalance method...".  The word "above" is an accessibility violation because assistive tools such as Jaws don't necessarily have a sense of above (or below).  So how about if you use "before" instead of "above"? Check to see if "above" and "below" are used elsewhere in the guide. If they are, change to appropriate wording, or sametime me for help. 

Change "After modifying your server.xml to include the fault tolerance feature, use the @fallback annotation to identify a method that runs when the Check Balance microservice fails." to "After you modify your `server.xml` file to include the fault tolerance feature, use the @fallback annotation to identify a method that runs when the Check Balance microservice fails."

**Comment by dmorgant** [comment]
Adjusted the statements as suggested above by Karen.  

**NOTE:  the use of before/after instead of above/below had already been completed in an earlier work item which had not been published yet.  Therefore, I did not have to make any of those changes with this work item.
