### ISSUE TITLE
Feedback for Circuit Breaker Guide

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/iguide-circuit-breaker#74]
A few thoughts for the team to consider:

- Transition between "Example: Bank Scenario" and "Enabling MicroProfile Fault Tolerance":  IMO, there is a pretty huge mental leap that is required as we move between these 2 sections.  We are walking through a scenario and then, suddenly, we are asking users to add a feature to the server.xml.  I think we can make it easier and explain the context and what we are trying to demonstrate and why better?

- Diagram in "Example: Bank Scenario":  Perhaps a better picture is in the works but the current one out there where the App is in the middle with links to 4 "Service[s]" at the corner doesn't seem to illustrate anything about the scenario or what we are trying to explain?

  - And, in general, I feel the "pipes" used in the graphics to indicate whether something is flowing through or not are difficult to understand.

- Perhaps it will help if we can explain what the users will be building to solve the problem before proceeding with the steps to build the solution.  Not in terms of the features that they will enable or use but the actual capabilities and problems that will be solved. 

- Definitions in "Configuring the failure threshold":  Definitions for requestVolumeThreshold and failureRatio are difficult to parse and understand on first read.  And, we don't call out the units either.  (So, what is 20 or 0.5?  How big or small are they?  Are they percentages or absolute numbers?  What is a rolling window?)  The example that follows is great to understand what they are but the definitions alone are difficult to understand.

  - I thought the graphics used in the interactive playground to show rolling window was pretty neat.  May be we can use similar techniques to explain the different parameters.

My 2 cents.

Tagging @lauracowen and @gcharters in case they have additional feedback.

**Comment by lauracowen** [comment]
I agree with YK's comments above. In addition, here are some things I noted down as I was going through:

* I like the introductory summary where it talks in simple language through what the guide will cover and what the user will learn from each bit.
* I think the Background Concepts bit works well too (in this particular guide at least) because the terms have already been introduced in the ‘What you’ll learn’ section
* I think the diagrams we have elsewhere should be in the same visual style as these ones.
* I’m not sure that the electrical circuit breaker analogy works if you don’t understand what a closed or open electrical circuit means. I don’t understand why a ‘closed circuit’ means that the system functions vs an ‘open circuit’ that means it is ‘incomplete’ - and does that mean it doesn’t function? I don’t follow the analogy. :(.  I agree with YK’s comment about pipes - I think it needs to be clearer what is achieved by this. eg what does a fully functional system mean in terms of what goes through the pipes? Okay, so I get that a ‘closed circuit’ means no break in the pipe vs ‘open circuit’ means there’s a break, but the term ‘closed’ and ‘open’ don’t imply that (eg ‘open for business’ means the opposite; also, ‘open’ feels like the opposite of ‘blocked’ but in this ‘open’ means the pipes are blocked *brain hurts*).
* The shading on the pipes makes it hard to tell whether there’s a difference in the content of the pipe on either side of the green/orange boxes. Wouldn’t it be easier to see a literal break in the pipe vs a complete pipe? In fact, going further through the guide, it’s not clear to me whether the lines/shading within the pipes are meant to show content of the pipes or just shading on the outside of the pipes.
* In general, I think it’s good to explain the circuit breaker with an analogy but I think this doesn’t quite work.
* Adding the @CircuitBreaker annotation: I think this needs a brief explanation of *why* you’re adding the default @CircuitBreaker policy. I don’t follow why we’re doing this at this stage. I know it’s explained more on the next page but I didn’t understand the previous page.
* Configuring the failure threshold:
* Rather than using the terms “The CircuitBreaker policy opens the circuit when…” why not just say “The CircuitBreaker policy breaks the circuit when…”. It’s a lot easier to understand without having to map the term ‘open’ to ‘broken’.
* Is it necessary to introduce the term ‘rolling window’ here? There’s no explanation of why it’s known as a rolling window and ‘rolling window’ doesn’t seem to be used in the code etc. If it needs to be introduced, I think it needs to be explained why the failure threshold is known as a rolling window. If it just means that the failure threshold is not a single figure but a rolling window of a range of figures (which I’m guessing is actually the case), I think this needs to be worded more clearly because ‘rolling window’ isn’t actually a new term for the concept (which the wording implies) but a description of how the failure threshold works.
* Should there be a new paragraph line break between “trigger.” and “For example”?
* Minor wording suggestion: “(2 requestVolumeThreshold x 0.5 failureRatio)” should come after “…2 requests” (before the comma) because it’s difficult to read the sentence as it currently stands.
* If you edit the code yourself (rather than clicking the button to do it), the Play button (the play icon) isn’t enabled and you have to click the 
* Configuring the success threshold page: Again, there seems to be a blank line missing between paragraphs.
* I like the summary (on the playground page) of what you’ve learned with suggestions of what to try changing and seeing what happens - we could do this in the static guides too.

**Comment by dmorgant** [comment]
Based on the feedback above the following items will be implemented.

- [ ] Under issue #19, Image updates and enhancements, we will be switching to some new images.  We are still working with design but the state diagrams will be a bit more distinctive with green, yellow, and red coloring used to emphasize the difference in the closed, half-open, and open states.  Another suggestion was to update the line flowing through the wire (not pipes!) to look more like a lightning bolt to emphasize the relationship of the circuit breaker concept to that used in an electrical system.

- [ ] 'Adding the @CircuitBreaker annotation' step - In the opening paragraph, add more of a blurb on why we are adding the @CB annotation similar to what we have in the From the 'What you'll learn' step where we indicate 'you'll include the @CircuitBreaker annotation so that your microservice fails immediately to prevent repeated calls that are likely to fail. '   Also, suggestion was made that saying 'default CircuitBreaker policy' may be confusing to the reader. This may be more clear by removing the word 'default', because we later explain each default value if they are not specified.

- [ ] In 'Configuring the  failure threshold' and the 'Playground' steps, we need to indicate that the brackets '[' ']' mean rolling window.  Review the definition of rolling window to see if any improvements can be made to emphasize that the term is a description of how the failure threshold works.

- [ ] In 'Configuring the failure threshold' step, get rid of the trailing space in 'The failureRatio parameter...' paragraph so that the sentence 'For example,...' doesn't look like its a new paragraph.  Specifically:
'...rolling window size before the circuit breaker can trigger. \<REMOVE SPACE HERE\>For example, when the requestVolumeThreshold parameter is ...'

- [ ] In 'Configuring the failure threshold' step, after selecting the Refresh button the first time, the description that slides in should be reworded to explain the math portion better. Have this description read more clearly.

- [ ] In 'Configuring the success threshold' step, the paragraph beginning with 'The default number of consecutive successes...' should have a blank line above it to emphasize that it is a separate paragraph.

**Comment by bcpswope** [comment]
labeling only to test doc bug/guide
